### PR TITLE
AttractRepulseSpartGeneratro and tests for it.

### PR DESCRIPTION
**Pull request by sleshJdev**

### CODE REVIEW

**Comment by tsimafei-markhel** [comment]
For some reason, this pull request contains not only AttractRepulseSparkGenerator and related stuff, but everything else that should not be merged for now. Can you look into this?

*I would suggest you not to commit .sln file at all.

**Comment by sleshJdev** [comment]
Hi, I removed the .sln file and other unnecessary files from the commit. Pull request is correct, I hope.

**Comment by tsimafei-markhel** [comment]
Great! Please fix the build first. https://ci.appveyor.com/project/tsimafei-markhel/fireworks/build/0.2.0.34

**Comment by tsimafei-markhel** [comment]
Merged, thank you!

**Pull request merged**
